name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:

  update-version:
    if: "!contains(github.event.head_commit.message, 'chore: update version')"
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}

      - run: |
          APP_NAME=$(jq -r '.name' version.json)
          VERSION=$(jq -r '.version' version.json)

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          MINOR=$((MINOR+1))
          PATCH=0
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"

          echo "{\"name\": \"$APP_NAME\", \"version\": \"$NEW_VERSION\"}" > version.json

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add version.json
          git commit -m "chore: update version to $NEW_VERSION"
          git push


  docker-push:
    needs: update-version
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Set APP_NAME and VERSION env vars
        run: |
          APP_NAME=$(jq -r '.name' version.json)
          VERSION=$(jq -r '.version' version.json)
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        timeout-minutes: 60
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:buildcache,mode=max